### ISSUE TITLE
Installed it but I see errors

### ISSUE THREAD

**Issue by Aquive** [bakman2/cryptofolio#1]
Nice piece of software. God job on that. I was just checking it out of curiosity. After installation I get two errors:

On top of the page:

Notice: Undefined variable: ticker in /public_html/crypto/portfolio.php on line 92

And for each coin it says:

Notice: Undefined index: coinValue in /public_html/crypto/index.phpon line 125

Also, is there a possibility to edit added coins?

**Comment by bakman2** [comment]
Thanks. There were some bugs indeed (will always be there ;)) 

Ticker error was fixed. 

Coin "edit" is a little overdone I think as there is not much to it other than a coin symbol and the number of coins, but I have made some changes to prevent issues when adding them. You can delete them by clicking on the icon.

**Comment by Aquive** [comment]
Thanks!
