### ISSUE TITLE
Sorteren

### ISSUE THREAD

**Issue by pven** [bakman2/cryptofolio#10]
Is het mogelijk om het overzicht te sorteren op basis van waar je op klikt? Dan denk ik vooral aan de naam van de coin of de totale waarde die erachter staat.

(Het werkt nu overigens prima bij mij snds de laatste updates.)

**Comment by bakman2** [comment]
Word onderdeel van meerdere enhancements.
https://github.com/bakman2/cryptofolio/issues/12
