### ISSUE TITLE
De coin SWEET zie ik niet meer

### ISSUE THREAD

**Issue by pven** [bakman2/cryptofolio#11]
Eerder deze week zag ik de coin SWEET in mijn lijstje staan, maar toen zag ik NYC niet. Nu is het andersom: ik zie NYC wel, maar SWEET weer niet.

Help? :-)

**Comment by bakman2** [comment]
Hoeveel waarde heeft die coin totaal in je port?
Hij moet onder “all” staan als ie weinig waarde heeft (<7 euro)

**Comment by pven** [comment]
Ik zie het al, hij was even onder de 7 euro gezakt. Opvallend overigens, want de waarde op YoBit is wat hoger.

Maar goed: opgelost dus. :-) Thx!

**Comment by bakman2** [comment]
Ja prijzen blijven lastig, de tool gebruikt cryptocompare; gemiddelde prijs van alle exchanges, soms loopt dat wat scheef. Op dit moment maakt het weinig uit, 1 groot bloedbad ;)
