### ISSUE TITLE
Undefined index (2x)

### ISSUE THREAD

**Issue by Aquive** [bakman2/cryptofolio#2]
Just updated to newest version with git pull. Thanks!

I am just reporting 2 more issues.

Notice: Undefined index: coins in /public_html/crypto/portfolio.php on line 11 (this one happens when there are no coins added)

Notice: Undefined index: coinValue in /public_html/crypto/index.php on line 128

Btw, if you'd like I can also fix it and do a pull request.

**Comment by bakman2** [comment]
I can fix them too no problem, I am not developing with full error messages, perhaps I should.

**Comment by bakman2** [comment]
The errors should be gone now. (others may pop up though 😔) 
I have modified some code for security, please read the install instructions.
