### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by Aquive** [bakman2/cryptofolio#3]
I just pulled newest version. Great to see the security improvement and Kucoin addition!

One error in the index.php still exists or am I doing something wrong? 
` Notice: Undefined index: coinValue in  ../public_html/crypto/index.php on line 119`

**Comment by bakman2** [comment]
You're right, coinValue shouldn't have been there. 
Error reporting on, I didn't get any more errors. Could you try again ?

**Comment by Aquive** [comment]
No errors so far! Thanks again.
