### ISSUE TITLE
Api import doesn't work anymore

### ISSUE THREAD

**Issue by hollander172** [bakman2/cryptofolio#5]
Since your last update the api import for Binance and Bittrex doesn't work anymore, those are the only exchanges I use so I don't know about the other ones. I made lib and config.json readable and writable, keys and secret codes appear in settings but still no go. I use cryptofolio on a synology.

**Comment by bakman2** [comment]
Hollander, heb je [de instructies](https://github.com/bakman2/cryptofolio/) gevolgd ? Ik heb onlangs een aantal zaken veranderd in de setup van de config voor de veiligheid, zou kunnen dat dat de reden is waarom het niet meer werkt voor je.

**Comment by hollander172** [comment]
Ik heb nu de vorige versie overschreven met als enige behoud de config.json. Ik kan nog een keer helemaal opnieuw beginnen? Bedankt voor je snelle antwoord trouwens!

**Comment by bakman2** [comment]
Je moet in ```config.php``` even het pad aangeven waar config.json staat. config.json moet wel de juiste rechten hebben, anders kan de webserver er niet mee omgaan. Overnieuw beginnen kan altijd natuurlijk, config.json kun je hergebruiken.

**Comment by hollander172** [comment]
Heb ik ook gedaan en als ik de settings open staan daar ook de keys in dus hij leest deze wel uit, dat is juist het vreemde en hij schrijft ze ook weg. Wat denk jij? Keertje helemaal opnieuw beginnen of is er iets anders mee aan de hand? In mijn beleving als het pad niet goed staat zou ik de keys ook niet moeten kunnen zien onder settings?

**Comment by bakman2** [comment]
Wat voor error(s) krijg je of blijft het leeg ? 
Opnieuw beginnen kan altijd uiteraard.

Klopt dat het zou moeten werken, maar er is iets anders loos.
Je zou in index.php dit onder `<?php` kunnen zetten:

```ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);```

opslaan en refresh, misschien dat er een error tevoorschijn komt.

**Comment by hollander172** [comment]
Daar ben ik niet handig genoeg voor, Syno geeft nu een 500 terug. Probeer wel een keertje helemaal overnieuw te beginnen. Geen errors dus, alles lijkt te werken alleen geen coins. Vorige versie werkte meer dan perfect dus waarom ik nou weer zo nodig moest updaten is me een raadsel.

**Comment by hollander172** [comment]
Helaas, ben helemaal opnieuw begonnen maar krijg het niet meer aan de praat. Ook voor de zekerheid nieuwe api key bij Binance aangemaakt maar het maakt geen verschil. Bij het invoeren van de key wordt deze netjes weggeschreven, ik snap dus niet goed wat er nu niet goed gaat... Lib/data is read- en writable. config.json dus ook.

**Comment by hollander172** [comment]
Nee Synology, heb in de web map een map crypto aangemaakt en daar cryptofolio ingezet, path is: /volume1/web/crypto/config.json en aangezien hij in de config dus wel keys wegschrijft snap ik niet zo goed waar het misgaat. 

En ja ik weet dat config.json niet de web map moet staan maar dit is even om te testen. Zodra ik het werkend heb pas ik de locatie wel aan.

**Comment by pven** [comment]
Ik heb op mijn Synology precies herzelfde, maar dan met Poloniex en Binance. Handmatig coins toevoegen werkt wel.

**Comment by hollander172** [comment]
Gelukkig ben ik niet de enige, Het werkte echt prima dus er moet ergens iets misgaan. Als ik ergens kan meedenken dan doe ik dat overigens graag, je hebt een meer dan prima product ontwikkeld, nou moeten de kinderziektes er nog uit.

**Comment by bakman2** [comment]
Laten we even gezellig blijven doen ;) Het draait bij meerdere mensen prima, dus ik zou niet meteen met het vingertje gaan wijzen.

**Comment by pven** [comment]
👍 

Als ik een api toevoeg dan duikt deze wel op in config.json, maar daarna krijg ik ook de 500-pagina en kan ik niets meer met de pagina. Handmatig de api verwijderen en dan de pagina verversen lost het op.

**Comment by hollander172** [comment]
Huh? Ik bedoelde het alleen maar goed? Wellicht heeft een update van Synology iets overhoop gehaald? Of is er ergens een instelling gewijzigd? Ik bied ook alleen mijn hulp aan?

**Comment by bakman2** [comment]
Voor deze versie zijn nieuwe API keys nodig voor bittrex en poloniex. Komt door een tijd calculatie.

**Comment by pven** [comment]
Voordat ik iets stuk maak: ik moet op Poloniex dus de bestaande api-key verwijderen en een nieuwe maken?

**Comment by bakman2** [comment]
Ja voor Binance had je dat al gedaan toch ?
Het is ff een gedoe maar hopelijk eenmalig. Komt omdat ik andere code gebruik om de api's aan te spreken van de exchanges

**Comment by pven** [comment]
Nee, maar ik ga het zo doen. Uiteraard kom ik er zo op terug.

**Comment by bakman2** [comment]
Voor Binance moet het ook helaas.

**Comment by hollander172** [comment]
Ik was degene die het voor Binance al gedaan had maar ik zal het weer opnieuw doen.

**Comment by bakman2** [comment]
De eerste keer dat je connect met de API houd ie een tijd bij wanneer je daar was, deze nieuwe code gebruikt een andere tijdcalculatie, dus de exchange zegt: dat accepteer ik niet.

**Comment by hollander172** [comment]
Dus alleen nieuwe api key of heb je ook changes aan de code gedaan?

**Comment by bakman2** [comment]
de code zelf heeft altijd changes ;)

**Comment by pven** [comment]
Voor Poloniex werkt het als ik een nieuwe api-key maak. Voor Binance heb ik ook een nieuwe api-key gemaakt, maar daarna krijg ik weer de 500-pagina in .

**Comment by pven** [comment]
Opvallend: als ik binance toevoeg, dan duiken binance en kucoin op in config.json. Voor binance zijn de velden ingevuld, voor kucoin zijn ze leeg.

**Comment by hollander172** [comment]
Dat code altijd changes heeft snap ik, het ging mij om de api interactie. Wil nog steeds best meedenken maar het wordt zo wel een beetje lastig. Hier geen 500 pagina, die krijg ik alleen als ik handmatig de boel verklooi.

**Comment by bakman2** [comment]
@pven, dan gaat er iets niet goed in de loop, ik ga er morgen naar kijken.  Zou ook @hollander172 zn probleem verklaren.  Vreemd dat het bij mij en anderen wel werkt, gebruik zelf binance,kucoin,polo en bittrex.

**Comment by pven** [comment]
Prima, uiteraard.

Is er een makkelijke manier om binance eruit te verwijderen? Ik heb wat zitten editten in config.json, maar het lukt me niet (of de 500-pagina, of geen coins meer). Zo niet, dan voer ik het handmatig weer in. :)

**Comment by bakman2** [comment]
als je je api/secret key weghaalt is ie weg.

**Comment by pven** [comment]
Top, dank je!

**Comment by bakman2** [comment]
Ik heb de boel herschreven voor API's, de meeste zitten er nu in. 

In de settings kun je nu direct API's toevoegen en weghalen, je kunt daarna op save klikken of handmatig de page refreshen. Als de exchange niet geladen kan worden, dan krijg je een error bovenin (de page laad verder wel). Mocht je exchange nog niet laden (die je nu hebt gedefineerd), haal hem even weg in de settings en voeg 'm opnieuw toe.

@pven ik vermoed dat je ze even moet weghalen dat je dat even moet doen voor dit issue:
>Opvallend: als ik binance toevoeg, dan duiken binance en kucoin op in config.json. Voor binance zijn de velden ingevuld, voor kucoin zijn ze leeg.

**Comment by bakman2** [comment]
@hollander172 het is makkelijker als je git installeert op je syno en een clone maakt van deze repo, dan kun je met 1 commando: `git pull` de updates binnenhalen zonder opnieuw te moeten downloaden en alles weer op zn plek te moeten zetten.

**Comment by bakman2** [comment]
Als het totaal minder is dan 5 euro of minder dan 0.009 coins (aantal), dan laat ie die coin niet zien.
Je bent met een lege config.json begonnen nu ?

**Comment by hollander172** [comment]
Ja echt helemaal overnieuw, niks bewaard en laatste versie erop gezet en ingesteld. Tegoeden moeten meer dan voldoende zijn om te laten zien.

**Comment by bakman2** [comment]
Je zegt "maar het probleem blijft hetzelfde" geen idee wat dat betekend. 
Maar de pagina laad en je krijgt geen error bovenaan in het rood ?

**Comment by bakman2** [comment]
@hollander172 ik heb het issue gevonden en aangepast.

**Comment by hollander172** [comment]
Oh sorry, pagina laad zoals het hoort zonder errors maar hij laat geen waarden zien terwijl ik wel voldoende tegoed heb op Binance.
![image](https://user-images.githubusercontent.com/35370856/34906420-c19e05a0-f86d-11e7-8b64-1056a46df750.png)

**Comment by bakman2** [comment]
Dat is vreemd, want er zat een issue in de code, maar dan had ie ook een error moeten geven bij het laden van binance  (in rood bovenaan).

**Comment by hollander172** [comment]
Ja ik snap het ook niet, zou zo graag willen dat ik een fout kon genereren zodat ik verder kan zoeken maar alles lijkt gewoon te werken. voor de zekerheid, ik heb aan mijn Synology ook niks veranderd in de tussentijd, ook geen updates gedaan nog.

**Comment by bakman2** [comment]
Je ziet in de settings binance erbij staan ?

![screen shot 2018-01-13 at 14 33 41](https://user-images.githubusercontent.com/333960/34906478-cca035a8-f86e-11e7-9a37-6bee69234986.jpg)

**Comment by kjw1985** [comment]
Volgens mij heb ik het zelfde probleem. Laatste versie net binnen getrokken, maar volgens mijn apache error log gaat het hier mis:

[Sat Jan 13 13:29:50.544809 2018] [php7:notice] [pid 9024] [client  IP:60758] PHP Notice:  Undefined index: action in /locatie/cryptofolio/editapi.php on line 15, referer: referer: http://IP/cryptofolio/

maar ook een undefined index action in editapi.php op line 32 en 49

Ik heb dus nieuw config.json bestand genomen, hierin wordt mijn api ook wel toegevoegd (Kucoin) maar username en password wil hij ook niet opslaan. Investment amount wel weer.

Hopelijk kan je hier iets mee. Als ik iets moet testen laat maar weten.

**Comment by bakman2** [comment]
Notice errors zijn geen errors maar notices ;) maar zal die afvangen zodat je ze niet meer krijgt. 
Username/password is een apart issue.

**Comment by hollander172** [comment]
Yup binance staat erbij zoals ik in het plaatje liet zien. Ik zal Bittrex eens toevoegen om te zien of die het wel doet en het dus wellicht ergens anders aan zou kunnen liggen.

**Comment by bakman2** [comment]
@hollander172 je hebt de laatste met de bugfix gebruikt ? https://github.com/bakman2/cryptofolio/issues/5#issuecomment-357434931

**Comment by hollander172** [comment]
Ja die van vandaag? Ben helemaal overnieuw begonnen.

**Comment by bakman2** [comment]
@hollander172  Nee die van 16 minuten geleden, maar goed ik weet nog steeds niet of je een rode balk bovenin krijgt te zien of niet.

**Comment by hollander172** [comment]
Nee geen balk maar ik zal nog eens helemaal overnieuw beginnen.

**Comment by pven** [comment]
Ik heb nu drie api's toegevoegd: binance, poloniex en yobit. Gisteren werkte poloniex, maar nu werkt er helemaal niets. Ik kan ze toevoegen, ik zie ze in config.json maar op de webpagina zie ik 'No coins added'.

Dien ik weer nieuwe api's te maken? (YoBit is net gemaakt, de rest gisteren.)

**Comment by hollander172** [comment]
Ja klopt, op een of andere manier hebben we hetzelfde probleem. Alles gedaan zoals aangegeven maar hij weigert helaas dienst. Geen errors, balkjes of wat dan ook. Alles lijkt normaal te functioneren maar er komt niks op de balans.

**Comment by bakman2** [comment]
Uitermate vreemd mannen. Ik en anderen hebben het op meerdere servers draaien zonder problemen.

Moeten wat debuggen. Download (https://gist.github.com/bakman2/2c27c2346b8dd09eb5c3eb4ac41de522)[deze file]  (noem hem debug.php of iets), zet hem in de hoofd directory en roep m aan in je browser. 

Wat voor output krijg je ?

**Comment by hollander172** [comment]
`debug...1 keys found.

binance: symbol: BTC : Bitcoin balance:0.00095876
binance: symbol: BNB : Binance Coin balance:89.95521529
binance: symbol: GAS : Gas balance:0.0831
binance: symbol: TRX : Tronix balance:10663
binance: symbol: XVG : Verge balance:0.8
binance: symbol: VEN : Vechain balance:132.867
binance: symbol: XRP : Ripple balance:0.988201
binance: symbol: XLM : Stellar balance:0.9674558

Array ( [0] => Array ( [symbol] => BNB [name] => Binance Coin [wallettype] => exchange [walletname] => binance [coinsOwned] => 89.95521529 [fullName] => Binance Coin (BNB) [image] => lib/data/bnb.png ) [1] => Array ( [symbol] => GAS [name] => Gas [wallettype] => exchange [walletname] => binance [coinsOwned] => 0.0831 [fullName] => Gas (GAS) [image] => lib/data/neo.jpg ) [2] => Array ( [symbol] => TRX [name] => Tronix [wallettype] => exchange [walletname] => binance [coinsOwned] => 10663 [fullName] => Tronix (TRX) [image] => lib/data/trx.png ) [3] => Array ( [symbol] => XVG [name] => Verge [wallettype] => exchange [walletname] => binance [coinsOwned] => 0.8 [fullName] => Verge (XVG) [image] => lib/data/xvg.png ) [4] => Array ( [symbol] => VEN [name] => Vechain [wallettype] => exchange [walletname] => binance [coinsOwned] => 132.867 [fullName] => Vechain (VEN) [image] => lib/data/ven.png ) [5] => Array ( [symbol] => XRP [name] => Ripple [wallettype] => exchange [walletname] => binance [coinsOwned] => 0.988201 [fullName] => Ripple (XRP) [image] => lib/data/ripple.png ) [6] => Array ( [symbol] => XLM [name] => Stellar [wallettype] => exchange [walletname] => binance [coinsOwned] => 0.9674558 [fullName] => Stellar (XLM) [image] => lib/data/str.png ) )`

**Comment by bakman2** [comment]
@pven nee nieuwe API keys hoeft niet, zou moeten werken. 
De data van @hollander172 laat zien dat ie het wel doet wel ophaalt (op dezelfde manier), maar er gaat nog ergens iets fout en ik zie het nog even niet, ga er morgen eens over nadenken wat er gaande is.

**Comment by hollander172** [comment]
Is het okee als ik mijn post weghaal? Nu staat mijn balance online en dat heb ik liever niet...

**Comment by bakman2** [comment]
Ja uiteraard!

**Comment by hollander172** [comment]
Okee mooi! Hoop dat je er iets mee kan. Helaas ben ik niet zo bedreven in php om je te kunnen helpen.

**Comment by pven** [comment]
Interessant: als ik handmatig een coin toevoeg, dan duiken poloniex en YoBit wel op in de lijst. Haal ik die coin weg, dan is de lijst weer leeg.

Kortom:
- handmatig coin toevoegen laat iig poloniex en YoBit zien
- binance wordt nog steeds niet getoond
- opvallend: ik heb de coin NYC op YoBit, die duikt niet op in de lijst

Als je meer info nodig hebt: laat maar weten

**Comment by pven** [comment]
Voor binance zie ik nu deze melding:
```
Error: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
```

Ik gok dat ik daar een nieuwe api moet maken?

**Comment by pven** [comment]
Nieuwe api voor binance maakt niets uit

**Comment by bakman2** [comment]
@pven 
>handmatig coin toevoegen laat iig poloniex en YoBit zien
Dit verklaart alles. thanks!  er stond een `}` op een verkeerde plek waardoor hij alleen de boel laat zien als er handmatig coins zijn toegevoegd. Zal zo een update maken.

Voor binance is het zaak dat je een ntp server gebruikt, als jouw systeem tijd ook maar iets afwijkt van die van binance, dan accepteert ie het niet (overigens geld dit voor meer servers).

Op je syno -> control panel -> regional options -> synchronise with timeserver -> pool.ntp.org. En update now klikken.

**Comment by bakman2** [comment]
Update staat erop. https://github.com/bakman2/cryptofolio/commit/c3abd4735037e88919c4bbbe91df9e61838cb2bf

**Comment by hollander172** [comment]
Solved! Thanks!

**Comment by pven** [comment]
Yes, het werkt. Thanks!

Ik heb nog wel wat issues die hier los van staan. Daar los ik vanavond ofzo nieuwe issues voor.

**Comment by bakman2** [comment]
@hollander172 Heb je deze coins wel ooit gehad en staat er nog balance (heel klein beetje) ? hij zou hier nooit mogen uitkomen als de balance op 0 staat.

**Comment by bakman2** [comment]
De errors zouden weg moeten zijn nu.
Als je meer dan 0.001 coin op de balans hebt dan laat ie zien.
