### ISSUE TITLE
IGNIS-coin toevoegen resulteert in raar totaal

### ISSUE THREAD

**Issue by pven** [bakman2/cryptofolio#6]
Als ik de IGNIS-coin toevoeg, dan wordt het totaal linksboven niet goed meer berekend. Als ik vervolgens handmatig in config.json deze coin weghaal en de pagina ververs, dan gaat het wel weer goed.

(Hoe kan ik via de webinterface een coin verwijderen?)

**Comment by bakman2** [comment]
Wat betekend "niet goed meer berekend" ? Is dit de juiste coin ? Zou kunnen dat de juiste er nog niet in zit. Verwijderen kun je door op het icon te klikken (alleen bij handmatig toegevoegde coins ofcourse)

**Comment by pven** [comment]
Dit staat er als ik hem toevoeg:
![image](https://user-images.githubusercontent.com/671621/34896714-310f0ebc-f7eb-11e7-998b-3db007a5ff09.png)
En mijn totaal verandert dan ook naar NaN

Verwijderen lukt inderdaad, dank. Als ik hem verwijder, is mijn totaal weer goed.

**Comment by bakman2** [comment]
Dit is een issue bij cryptocompare (daar komen prijs update vandaan), ze sturen geen data via de socket als je IGNIS opvraagt. Zullen moeten wachten tot ze die hebben toegevoegd.

**Comment by pven** [comment]
Is het dan misschien een idee om het totaal wel te berkenen? Daar komt nu ook NaN te staan.

**Comment by bakman2** [comment]
Het heeft weinig zin om een coin in je port te zien die geen waarde kan laten zien?

**Comment by pven** [comment]
IGNIS is een geval apart ;)

Ik heb deze coin in een wallet zitten, hij staat al op een paar exchanges en heeft dus wel degelijke waarde. Maar mainstream is ie nog zeker niet.

**Comment by bakman2** [comment]
Ik haal hem liever uit de lijst totdat er wel data is.

**Comment by bakman2** [comment]
Ik heb IGNIS er voor nu even uit gehaald. Ik hou in de gaten of ie gaat werken.
