### ISSUE TITLE
YoBit-api toevoegen

### ISSUE THREAD

**Issue by pven** [bakman2/cryptofolio#7]
Is het mogelijk om de YoBit-api ook toe te voegen?

Thx!

**Comment by bakman2** [comment]
Ja ik zal het op dezelfde manier maken zoals een coin toevoegen. Moet er even over nadenken wat wijsheid is.

**Comment by bakman2** [comment]
Ik heb de settings herschreven, de meest API's zijn nu beschikbaar.

**Comment by pven** [comment]
Deze werk dus. Thx! :)
