### ISSUE TITLE
TRX verdwijnt uit overzicht, zowel via API als handmatige invoer

### ISSUE THREAD

**Issue by Cafun** [bakman2/cryptofolio#9]
Ik heb 50 TRX, echter wordt deze niet weergegeven. Als ik de pagina ververs met F5, zie ik hem een fractie van een seconde ertussen staan, maar verdwijnt dan weer. Ik gebruik de API van Binance. Maar ook als ik TRX handmatig toevoeg, verdwijnt hij uit mijn overzicht.

Ik gebruik een Synology en heb cryptofolio al een keer verwijderd en opnieuw ingesteld.
Ik weet even niet of ik iets verkeerd doe, of dat het mogelijk toch een bug is.

Alvast bedankt voor het meedenken!

**Comment by bakman2** [comment]
Doe geen moeite met verwijderen en etc; 
Trx is 0.06*50 = 3 euro. Minder dan 5 euro word verwijderd uit de lijst.

**Comment by Cafun** [comment]
Ah bedankt voor de snelle reactie.
Mag ik dan een feature request doen om het optioneel te maken dat het verwijderd wordt? Ikzelf zou bijvoorbeeld gewoon al mijn coins willen zien die ik heb.

**Comment by bakman2** [comment]
Er zijn coins die je niet kunt verkopen als het er te weinig zijn, ondanks dat ze een waarde hebben.
Ik heb de filters aangepast, < 7 euro staan in ALL lijst.
